app_servers:
  hosts:
    app1:
      ansible_host: '35.173.196.238' # Fill in your "app" instance's public IP address here

db_servers:
  hosts:
    db1:
      ansible_host: '34.238.142.12' # Fill in your "db" instance's public IP address here

# Look up the Ansible documentation to work out what this block does
all_servers:
  children:
    app_servers:
    db_servers:
